import { defineCollection, reference, z } from 'astro:content';
import { glob, file } from 'astro/loaders';

const link = z.string().url();

/** Generated by scripts/ingest_publications.py from data/publications.xlsx + data/pub_meta.json. Do not edit by hand. */
const publications = defineCollection({
  loader: file('./src/data/publications.json'),
  schema: z.object({
    id: z.string(),                         // stable slug, the URL
    ref: z.string(),                        // workbook 編號 (A1, B3 …): positional, never used in URLs
    type: z.enum(['journal', 'conference', 'book', 'other']),
    year: z.number().int(),
    authors: z.array(z.string()),
    title: z.string(),
    venue: z.string().optional(),
    venueShort: z.string().optional(),
    location: z.string().optional(),
    locationZh: z.string().optional(),
    date: z.string().optional(),
    publisher: z.string().optional(),
    volume: z.string().optional(),
    pages: z.string().optional(),
    isbn: z.string().optional(),
    role: z.string().optional(),
    doi: z.string().optional(),
    doiUrl: link.optional(),
    url: z.string().optional(),
    pdf: z.string().optional(),
    indexing: z.string().optional(),
    format: z.string().optional(),
    openAccess: z.boolean().default(false),
    apa: z.string().optional(),
    abstract: z.string().optional(),
    theme: z.string().optional(),           // thread id
    featured: z.number().int().positive().optional(),   // rank on the home page, 1 = first
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    video: z.string().optional(),
  }),
});

/** Research threads. `line` is the one-line summary used on the home page. */
const themes = defineCollection({
  loader: file('./src/data/themes.json'),
  schema: z.object({
    id: z.string(),
    order: z.number(),
    name: z.string(),
    name_zh: z.string(),
    label: z.string(),                      // short name for filters and badges
    label_zh: z.string(),
    color: z.string().regex(/^#[0-9a-f]{6}$/i),
    line: z.string(),
    line_zh: z.string(),
    summary: z.string(),
    summary_zh: z.string(),
    description: z.string(),
    description_zh: z.string(),
  }),
});

/**
 * People: one Markdown file per person in src/content/people/. The front matter is written by
 * scripts/ingest_people.py from data/people.xlsx; the body (English bio) and bio_zh are edited here.
 */
const people = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/people' }),
  schema: z.object({
    name: z.string(),
    name_zh: z.string().optional(),
    role: z.enum(['director', 'faculty', 'postdoc', 'phd', 'master', 'researcher', 'assistant', 'alumni']),
    title: z.string().optional(),           // "PhD candidate", "Associate Professor"
    title_zh: z.string().optional(),
    affiliation: z.string().optional(),     // current position elsewhere, e.g. "Assistant Professor, …"
    affiliation_zh: z.string().optional(),
    cohort: z.number().int().optional(),    // ROC entry year, e.g. 113
    years: z.string().optional(),           // "2021–"
    degree: z.string().optional(),          // alumni: "MS 2025"
    email: z.string().optional(),
    image: z.string().optional(),           // /images/people/<id>.jpg, 4:5
    links: z
      .object({
        website: link.optional(),
        linkedin: link.optional(),
        scholar: link.optional(),
        orcid: link.optional(),
        github: link.optional(),
        gitlab: link.optional(),
        instagram: link.optional(),
        cv: link.optional(),
        nycu: link.optional(),              // NYCU Academic Hub profile
      })
      .default({}),
    bio_zh: z.string().optional(),
    order: z.number().default(100),
    publish: z.boolean().default(true),     // false = kept in the data, never shown
    confirmed: z.boolean().default(true),   // false = some fields (usually the English name) still to check
  }),
});

/**
 * Theses supervised in the lab. Generated by scripts/ingest_people.py from data/people.xlsx
 * (sheets `theses` and `thesis_figures`) — do not edit by hand.
 */
const figure = z.object({
  src: z.string(), srcSm: z.string(), w: z.number(), h: z.number(),
  caption: z.string().optional(), caption_zh: z.string().optional(),
  focus: z.string().optional(), main: z.boolean().default(false),
});
const theses = defineCollection({
  loader: file('./src/data/theses.json'),
  schema: z.object({
    id: z.string(),                         // e.g. ms2025-hung-wen-lu
    person: reference('people'),
    degree: z.enum(['MS', 'PhD']),
    year: z.number().int(),
    university: z.string().optional(),      // NCTU (to 2020) | NYCU
    department: z.string().optional(),
    department_zh: z.string().optional(),
    title: z.string(),
    title_zh: z.string().optional(),
    thread: reference('themes').optional(),
    pubs: z.array(reference('publications')).default([]),   // publication slugs
    keywords: z.array(z.string()).default([]),
    keywords_zh: z.array(z.string()).default([]),
    abstract: z.string().optional(),
    abstract_zh: z.string().optional(),
    coAdvisors: z.string().optional(),
    libraryUrl: link.optional(),
    ndltdUrl: link.optional(),
    doi: z.string().optional(),
    link: z.string().optional(),
    image: z.string().optional(),           // main figure
    imageSm: z.string().optional(),         // 800 px copy for grids
    focus: z.string().optional(),           // CSS object-position for the crop
    figures: z.array(figure).default([]),
  }),
});

/**
 * Activities: exhibitions, festivals, curation, funded projects, conferences, talks, workshops,
 * juries, awards, media coverage and writing. Body = English text. Written by
 * scripts/make_activities.py until the lab starts editing the files by hand.
 */
const activities = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/activities' }),
  schema: z.object({
    title: z.string(),
    title_zh: z.string().optional(),
    type: z.enum([
      'exhibition', 'festival', 'curation', 'conference', 'talk', 'workshop',
      'jury', 'award', 'grant', 'press', 'writing',
    ]),
    year: z.number().int(),
    date: z.string().optional(),            // ISO start date, sort key within a year: "2026-06-11"
    dateLabel: z.string().optional(),       // "2026.06.11–06.21"
    venue: z.string().optional(),           // exhibitions: venue · press: outlet
    venue_zh: z.string().optional(),
    place: z.string().optional(),
    place_zh: z.string().optional(),
    work: z.string().optional(),            // work shown: "Animabotany"
    work_zh: z.string().optional(),
    credit: z.string().optional(),          // one line on who did what
    credit_zh: z.string().optional(),
    people: z.array(z.string()).default([]),   // names as credited (not all are People entries)
    funder: z.string().optional(),
    funder_zh: z.string().optional(),
    grantId: z.string().optional(),
    link: link.optional(),
    image: z.string().optional(),
    summary_zh: z.string().optional(),
    sources: z.array(link).default([]),     // where each fact was checked; not rendered
    publications: z.array(reference('publications')).default([]),   // publication slugs
    featured: z.boolean().default(false),   // eligible for the home page
    draft: z.boolean().default(false),
  }),
});

/** Projects: multi-paper umbrellas (a funded project, a research series). */
const projects = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/projects' }),
  schema: z.object({
    title: z.string(),
    title_zh: z.string().optional(),
    theme: reference('themes'),
    years: z.string().optional(),
    summary: z.string(),
    summary_zh: z.string().optional(),
    people: z.array(reference('people')).default([]),
    publications: z.array(reference('publications')).default([]),
    image: z.string().optional(),
    link: link.optional(),
    order: z.number().default(100),
  }),
});

/** Long-form pages (About) kept per language: src/content/pages/<lang>/<slug>.md */
const pages = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    lede: z.string().optional(),
    excerpt: z.array(z.string()).default([]),   // paragraphs shown in the home preview
  }),
});

export const collections = { publications, themes, theses, people, activities, projects, pages };
